{{- if .Values.preJob.preInitDB.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
{{ include "service.labels.standard" . | indent 4 }}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: {{ .Values.preJob.timeout | default 300 }}
  template:
    metadata:
      name: {{ .Release.Name }}-init-db
    spec:
      initContainers:
      - command:
        - sh
        - -c
        - cp -rfp /var/choerodon/* /tools
        image: {{ .Values.preJob.image }}
        imagePullPolicy: IfNotPresent
        name: tools
        volumeMounts:
        - mountPath: /tools
          name: tools-jar
      containers:
      - name: {{ .Release.Name }}-init-db
        image: {{ include "service.image" . }}
        command:
        - /bin/sh
        - -c
        - >
          java -Ddata.init=true
          -Dspring.datasource.url="{{ .Values.preJob.preInitDB.datasource.url }}"
          -Dspring.datasource.username={{ .Values.preJob.preInitDB.datasource.username }}
          -Dspring.datasource.password={{ .Values.preJob.preInitDB.datasource.password }}
          -Dspring.datasource.driver-class-name={{ .Values.preJob.preInitDB.datasource.driver }}
          -Dinstaller.datasources.platform.url="{{ .Values.preJob.preInitDB.datasources.platform.url }}"
          -Dinstaller.datasources.platform.username={{ .Values.preJob.preInitDB.datasources.platform.username }}
          -Dinstaller.datasources.platform.password={{ .Values.preJob.preInitDB.datasources.platform.password }}
          -Dinstaller.datasources.platform.driver-class-name={{ .Values.preJob.preInitDB.datasources.platform.driver }}
          -Dinstaller.datasources.message.url="{{ .Values.preJob.preInitDB.datasources.message.url }}"
          -Dinstaller.datasources.message.username={{ .Values.preJob.preInitDB.datasources.message.username }}
          -Dinstaller.datasources.message.password={{ .Values.preJob.preInitDB.datasources.message.password }}
          -Dinstaller.datasources.message.driver-class-name={{ .Values.preJob.preInitDB.datasources.message.driver }}
          -Dinstaller.jarPath=/choerodon/{{ .Chart.Name }}.jar
          -Dlogging.level.root=info
          -Dinstaller.mapping=script/db/service-mapping.xml
          -jar /var/choerodon/choerodon-tool-liquibase.jar;
        volumeMounts:
        - mountPath: /var/choerodon
          name: tools-jar
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: tools-jar
{{- end }}