{{- if .Values.preJob.preInitDB.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-db
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
  labels:
{{ include "service.labels.standard" . | indent 4 }}
spec:
  backoffLimit: 1
  activeDeadlineSeconds: {{ .Values.preJob.timeout | default 300 }}
  template:
    metadata:
      name: {{ .Release.Name }}-init-db
    spec:
      initContainers:
      - command:
        - sh
        - -c
        - cp -rf /var/choerodon/* /tools
        image: {{ .Values.preJob.image }}
        imagePullPolicy: Always
        name: tools
        volumeMounts:
        - mountPath: /tools
          name: tools-jar
      containers:
      - name: {{ .Release.Name }}-init-db
        image: "{{ .Values.image.repository }}:{{ .Chart.Version }}"
        command:
        - /bin/sh
        - -c
        - '
          java -Dspring.datasource.url="{{ .Values.preJob.preInitDB.datasource.url }}" -Dspring.datasource.username={{ .Values.preJob.preInitDB.datasource.username }} -Dspring.datasource.password={{ .Values.preJob.preInitDB.datasource.password }} -Ddata.init=true -Ddata.update.exclusion={{ .Values.preJob.preInitDB.datasource.exclusion }} -Ddata.jar=/{{ .Chart.Name }}.jar -jar /var/choerodon/choerodon-tool-liquibase.jar;
          '
        volumeMounts:
        - mountPath: /var/choerodon
          name: tools-jar
      restartPolicy: Never
      volumes:
      - emptyDir: {}
        name: tools-jar
{{- end }}